name: GitHub Main Workflow

on: [push, workflow_dispatch]

permissions:
  checks: write
  actions: read
  contents: read
  pull-requests: write
  issues: read
jobs:
  build: 
    runs-on: windows-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Active direcory
        run: echo "$GITHUB_WORKSPACE"
      # Compile notre application

          
      # Build l'image Docker
      - name: Docker build
        run: |
          docker build .
